// <auto-generated />
namespace NLayerApp.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Phones : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Phones));
        
        string IMigrationMetadata.Id
        {
            get { return "202310210756319_Phones"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
